# -*- coding: utf-8 -*-
"""Rulebase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fI-QtI6lTzrmfpPsfvh_vGdHONr98h1

This is the OG code before converted into biometric_analyzer for android use. This only runs on PC
"""

# ============================================
# Biometric Scan Analyzer → scores + recommendations
# ============================================
import os, glob, json, re
import pandas as pd
import numpy as np

# Optional: ML anomaly (comment these 3 lines if you don't want it)
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import MinMaxScaler

# --------- CONFIG ---------
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Adjust this folder name to match your exact Drive folder
DATA_DIR = "/content/drive/MyDrive/Biometric_Data"   # or FYP_Biometric_Data

# Output files (optional)
OUT_CSV  = os.path.join(DATA_DIR, "scans_with_recommendations.csv")
OUT_JSON = os.path.join(DATA_DIR, "scans_with_recommendations.json")

print("✅ Drive mounted successfully!")
print("📂 Data directory:", DATA_DIR)


files = glob.glob(os.path.join(DATA_DIR, "*.json"))
print(f"✅ Found {len(files)} JSON files")

# --------- Helpers ---------
def text_contains(raw, pattern):
    return bool(re.search(pattern, raw, flags=re.IGNORECASE))

WEAKNESS_TO_CWE = {
    "Negative button bypass": ["CWE-306"],
    "Deprecated API usage": ["CWE-749"],
    "Missing crypto object validation": ["CWE-310"],
    "Network transfer detected (no TLS/pinning)": ["CWE-319","CWE-295"],
    "Unencrypted biometric templates / storage": ["CWE-319"],
    "API hook / instrumentation": ["CWE-693"],
    "Fast auth timing": ["CWE-208"],
    "Excessive retries / no timeout": ["CWE-307"],
}

RECS = {
    "Negative button bypass": "Use BiometricPrompt with device-credential fallback (setDeviceCredentialAllowed(true)); remove negative button text.",
    "Deprecated API usage": "Migrate from FingerprintManager to androidx.biometric.BiometricPrompt.",
    "Missing crypto object validation": "Bind auth to CryptoObject backed by Android Keystore; enforce key attestation and auth-required flags.",
    "Network transfer detected (no TLS/pinning)": "Require TLS 1.2+ with strong ciphers and implement certificate pinning; never send raw templates.",
    "Unencrypted biometric templates / storage": "Do not store biometric templates on disk; keep keys in hardware-backed keystore only.",
    "API hook / instrumentation": "Detect Frida/Xposed; block sensitive ops in debug/compromised environments; add anti-tamper.",
    "Fast auth timing": "Investigate timing anomalies; add randomized delays/jitter and enforce sensor-read latency bounds.",
    "Excessive retries / no timeout": "Enforce retry limits and authentication timeouts to reduce abuse/spoof attempts."
}

WEIGHTS = {
    "hooked": 40,
    "negative_button": 40,
    "deprecated_api": 20,
    "no_crypto": 30,
    "network_insecure": 30,
    "template_storage": 25,
    "fast_duration": 20,
    "retry_excess": 15,
}

# --------- Load all JSONs ---------
files = sorted(glob.glob(os.path.join(DATA_DIR, "*.json")))
rows = []

for f in files:
    try:
        with open(f, "r", encoding="utf-8") as fh:
            j = json.load(fh)
    except Exception:
        continue

    raw = json.dumps(j, ensure_ascii=False)
    meta = j.get("metadata", {}) if isinstance(j, dict) else {}
    sessions = j.get("biometricSessions") if isinstance(j, dict) else None
    session = sessions[0] if isinstance(sessions, list) and sessions else {}

    vuln_list        = j.get("vulnerabilities", []) if isinstance(j, dict) else []
    api_findings     = j.get("apiFindings", []) if isinstance(j, dict) else []
    crypto_findings  = j.get("cryptoFindings", []) if isinstance(j, dict) else []
    network_findings = j.get("networkFindings", []) if isinstance(j, dict) else []
    storage_findings = j.get("storageFindings", []) if isinstance(j, dict) else []
    memory_findings  = j.get("memoryFindings", []) if isinstance(j, dict) else []
    timing           = j.get("timingData", {}) if isinstance(j, dict) else {}

    # Derived flags from structured + raw text
    neg_btn = 0
    dep_api = 0
    for v in vuln_list:
        title = (v.get("title") or "").lower()
        cat   = (v.get("category") or "").lower()
        tech  = json.dumps(v.get("technicalDetails", {})).lower()
        if "negative button" in title or "negative" in title:
            neg_btn = 1
        if "deprecated" in cat or "fingerprintmanager" in tech:
            dep_api = 1

    if not dep_api and "fingerprintmanager" in raw.lower():
        dep_api = 1

    # Crypto present: prefer structured finding, else fall back to session.hasCrypto
    has_crypto = 1 if crypto_findings else int(bool(session.get("hasCrypto", False)))

    net_flag = 1 if network_findings else (1 if re.search(r"\b(post|fetch|http|https|socket\.send)\b", raw, re.I) else 0)
    tls_ok   = bool(re.search(r"TLSv1\.\d|TLSv2|cipher|pinning", raw, re.I))

    store_flag  = 1 if storage_findings else (1 if re.search(r"FileOutputStream|/sdcard|external|write\(", raw, re.I) else 0)
    hooked_flag = 1 if re.search(r"\bHOOKED\b|\bFrida\b|\bXposed\b|\blibfrida\b", raw, re.I) else 0

    attempts = timing.get("attempts", []) if isinstance(timing, dict) else []
    retry_count = len(attempts)
    durations = []
    for a in attempts:
        d = a.get("duration", 0) if isinstance(a, dict) else 0
        try:
            durations.append(float(d or 0))
        except:
            durations.append(0.0)
    avg_duration = float(np.mean(durations)) if durations else 0.0
    min_duration = float(np.min(durations)) if durations else 0.0

    # Older schema fallback
    try:
        durationMs = float(session.get("durationMs") or 0)
    except:
        durationMs = 0.0
    result = (session.get("result") or "").lower()

    rows.append({
        "file": os.path.basename(f),
        "scan_id": meta.get("scanId", os.path.basename(f)),
        "timestamp": meta.get("timestamp"),
        "api": session.get("api",""),
        "result": result,
        "hasCrypto": int(bool(has_crypto)),
        "durationMs": durationMs,
        "negative_button_flag": int(neg_btn),
        "deprecated_api_flag": int(dep_api),
        "network_flag": int(net_flag),
        "tls_ok_hint": int(tls_ok),
        "storage_flag": int(store_flag),
        "hooked_flag": int(hooked_flag),
        "retry_count": int(retry_count),
        "avg_duration": avg_duration,
        "min_duration": min_duration,
        "vuln_count": len(vuln_list),
        "has_vulnerabilities_block": int(bool(vuln_list)),
        "has_apiFindings_block": int(bool(api_findings)),
        "has_cryptoFindings_block": int(bool(crypto_findings)),
        "has_networkFindings_block": int(bool(network_findings)),
        "has_storageFindings_block": int(bool(storage_findings)),
        "has_memoryFindings_block": int(bool(memory_findings)),
        "raw": raw  # keep for reference if you want, remove for smaller output
    })

df = pd.DataFrame(rows)

# ============================================
# RULE-BASED SCORING ENGINE (FIRST VERSION)
# ============================================

def compute_rule_score_safe(r):
    try:
        score = 0
        evidence = []

        if r.get('hooked_flag', 0):
            score += WEIGHTS.get('hooked', 0)
            evidence.append("HOOKED/Frida/Xposed detected")
        if r.get('negative_button_flag', 0):
            score += WEIGHTS.get('negative_button', 0)
            evidence.append("Negative button in BiometricPrompt")
        if r.get('deprecated_api_flag', 0):
            score += WEIGHTS.get('deprecated_api', 0)
            evidence.append("Deprecated Fingerprint API in use")
        if not r.get('hasCrypto', 1):
            score += WEIGHTS.get('no_crypto', 0)
            evidence.append("No CryptoObject / Keystore missing")
        if r.get('network_flag', 0) and not r.get('tls_ok_hint', 1):
            score += WEIGHTS.get('network_insecure', 0)
            evidence.append("Network transfer without TLS/pinning evidence")
        if r.get('storage_flag', 0):
            score += WEIGHTS.get('template_storage', 0)
            evidence.append("Possible on-disk template/storage write")

        fast_ms = r.get('min_duration', 0) or r.get('durationMs', 0)
        if fast_ms and isinstance(fast_ms, (int, float)) and fast_ms < 100:
            score += WEIGHTS.get('fast_duration', 0)
            evidence.append(f"Very fast timing ({fast_ms:.1f} ms)")
        if isinstance(r.get('retry_count', 0), (int, float)) and r.get('retry_count', 0) > 3:
            score += WEIGHTS.get('retry_excess', 0)
            evidence.append(f"Excessive retries: {r['retry_count']}")

        # Always return exactly two values
        return [min(100, score), "; ".join(evidence)]
    except Exception as e:
        # Always return a two-element fallback
        return [0, f"Error: {e}"]

# ---- guaranteed-safe assignment ----
df[['rule_score', 'evidence']] = pd.DataFrame(
    df.apply(lambda r: compute_rule_score_safe(r), axis=1).tolist(),
    index=df.index
)

print("✅ Rule-based scores and evidence computed successfully.")
display(df[['file', 'rule_score', 'evidence']].head())

# --------- (Optional) anomaly score ---------
feat_cols = ["negative_button_flag","deprecated_api_flag","hasCrypto","network_flag","tls_ok_hint",
             "storage_flag","hooked_flag","retry_count","avg_duration","min_duration","durationMs","vuln_count"]
X = df[feat_cols].fillna(0).astype(float)
if len(df) >= 8:
    iso = IsolationForest(contamination=0.15, random_state=42)
    iso_pred = iso.fit_predict(X)  # -1 anomaly, 1 normal
    anomaly_raw = (iso_pred == -1).astype(int)
    scaler = MinMaxScaler()
    df['anomaly_score'] = scaler.fit_transform(anomaly_raw.reshape(-1,1).astype(float))
else:
    df['anomaly_score'] = 0.0

df['final_risk_score'] = (0.75 * df['rule_score'] + 0.25 * (df['anomaly_score'] * 100)).round(0).astype(int)

# --------- Weakness objects & recommendations ---------
def build_weaknesses_and_recs(row):
    weaknesses, recs = [], []

    def add(name, code, severity, score, evidence):
        item = {"name": name, "code": code, "severity": severity, "score": int(score), "evidence": evidence}
        item["cwe"] = WEAKNESS_TO_CWE.get(name, [])
        weaknesses.append(item)
        r = RECS.get(name) or ""
        if r and r not in recs:
            recs.append(r)

    if row['hooked_flag']:
        add("API hook / instrumentation","HOOK_INTR","CRITICAL",WEIGHTS['hooked'], "HOOKED/Frida/Xposed present")
    if row['negative_button_flag']:
        add("Negative button bypass","API_NEG_BTN","HIGH",WEIGHTS['negative_button'], "Negative button in prompt config")
    if row['deprecated_api_flag']:
        add("Deprecated API usage","API_DEPRECATED","MEDIUM",WEIGHTS['deprecated_api'], "FingerprintManager usage")
    if not row['hasCrypto']:
        add("Missing crypto object validation","API_CRYPTO_MISSING","HIGH",WEIGHTS['no_crypto'], "No CryptoObject/Keystore evidence")
    if row['network_flag'] and not row['tls_ok_hint']:
        add("Network transfer detected (no TLS/pinning)","NET_INSECURE","HIGH",WEIGHTS['network_insecure'], "Network activity without TLS/pinning evidence")
    if row['storage_flag']:
        add("Unencrypted biometric templates / storage","STORAGE_TEMPLATES","HIGH",WEIGHTS['template_storage'], "Possible file writes / template storage")
    fast_ms = row['min_duration'] if row['min_duration'] > 0 else (row['durationMs'] if row['durationMs']>0 else 0)
    if fast_ms and fast_ms < 100:
        add("Fast auth timing","TIMING_FAST","HIGH",WEIGHTS['fast_duration'], f"Very fast timing {fast_ms:.1f} ms")
    if row['retry_count'] > 3:
        add("Excessive retries / no timeout","RETRY_EXCESS","MEDIUM",WEIGHTS['retry_excess'], f"{row['retry_count']} attempts")

    return weaknesses, recs

df[['weaknesses','recommendations']] = df.apply(lambda r: pd.Series(build_weaknesses_and_recs(r)), axis=1)

# --------- Export ---------
export_cols = [
    "file","scan_id","timestamp","api","result",
    "hasCrypto","durationMs","negative_button_flag","deprecated_api_flag",
    "network_flag","tls_ok_hint","storage_flag","hooked_flag",
    "retry_count","avg_duration","min_duration","vuln_count",
    "rule_score","anomaly_score","final_risk_score","weaknesses","recommendations"
]

export_df = df[export_cols].copy()
export_df.to_csv(OUT_CSV, index=False)
export_df.to_json(OUT_JSON, orient="records", indent=2, force_ascii=False)

print(f"✅ Saved:\n - {OUT_CSV}\n - {OUT_JSON}")
print("\nTop 10 by risk:")
print(export_df.sort_values("final_risk_score", ascending=False).head(10)[
    ["file","api","result","final_risk_score","rule_score","anomaly_score","weaknesses"]
].to_string(index=False))





from google.colab import drive
drive.mount('/content/drive')

!cp biometric_model.tflite /content/drive/MyDrive/
print("✅ Saved to Google Drive: /MyDrive/biometric_model.tflite")